spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/pay_appdb;
     username: postgres
     password: 1234
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
  
my:
  mail:
    host: smtp.gmail.com
    port: 587
    username: payapp244@gmail.com
    password: lkeqizmirjtuatqv
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.auth: true

      
